#! /bin/sh

# Autostart
xrandr --output eDP1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP1 --off --output DP2 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off --left-of eDP1
setxkbmap us &
# xrdb -load $HOME/.config/.Xresources &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
dunst -conf $HOME/.config/dunst/dunstrc &
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
$HOME/.config/polybar/launch.sh &

# Workspaces
bspc monitor DP2 -d I II III IV
bspc monitor eDP1 -d V VI VII VIII

bspc rule -a nautilus desktop='^VI'
bspc rule -a chromium desktop='^V'
bspc rule -a code desktop='^IV'

# Other stuff
bspc config border_width         0
bspc config window_gap           16
bspc config split_ratio          .55
bspc config top_padding          34
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"
