#! /bin/sh

# Autostart
if [[ $(xrandr -q | grep 'DP2 connected') ]]; then
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal  --output DP2 --mode 1920x1080 --rotate normal --left-of eDP1
fi
setxkbmap us &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
dunst -conf $HOME/.config/dunst/dunstrc &
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
redshift-gtk &
$HOME/.config/polybar/launch.sh &

# Workspaces
bspc monitor DP2 -d V VI VII VIII &
bspc monitor eDP1 -d I II III IV &
# startup

bspc rule -a nautilus desktop='^VI'
bspc rule -a chromium desktop='^V'
bspc rule -a code desktop='^IV'
bspc rule -a vlc state=floating

# Other stuff
bspc config border_width         2
bspc config window_gap           16
bspc config split_ratio          .50
bspc config top_padding          24
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#616161"
